[build]
  base = "vaxsync"
  command = "npm run build"
  publish = ".next"
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/pages/signin"
  status = 200

[functions]
  directory = "netlify/functions"